import type { Category, Question } from "./types";

// Seed rows omit answerLocked — the DB defaults it to false on insert.
type SeedQuestion = Omit<Question, "answerLocked">;

// Phase 0 seed data. In Phase 1 this file is replaced by Supabase queries;
// nothing else in the app imports the data directly — it all goes through
// src/lib/data.ts, so the swap is contained.

export const categories: Category[] = [
  { id: "c01", name: "Introduction", description: "Tell-me-about-yourself and career introduction", sortOrder: 1 },
  { id: "c02", name: "Current Role", description: "Day-to-day, responsibilities, team", sortOrder: 2 },
  { id: "c03", name: "o9 Platform", description: "o9 platform, IBPL, modules, planning", sortOrder: 3 },
  { id: "c04", name: "Project Experience", description: "Current/past project questions and scenarios", sortOrder: 4 },
  { id: "c05", name: "Supply Chain", description: "Demand, supply, S&OP concepts", sortOrder: 5 },
  { id: "c06", name: "Integration", description: "Data integration, connectors, pipelines", sortOrder: 6 },
  { id: "c07", name: "SQL", description: "Queries, tuning, modeling", sortOrder: 7 },
  { id: "c08", name: "PySpark", description: "DataFrames, transformations, tuning", sortOrder: 8 },
  { id: "c09", name: "Spark", description: "Execution model, internals", sortOrder: 9 },
  { id: "c10", name: "Databricks", description: "Jobs, clusters, Delta", sortOrder: 10 },
  { id: "c11", name: "Azure", description: "ADF, ADLS, Synapse", sortOrder: 11 },
  { id: "c12", name: "AWS", description: "S3, Glue, EMR, Redshift", sortOrder: 12 },
  { id: "c13", name: "Scenario Based", description: "Production issues, failures, debugging", sortOrder: 13 },
  { id: "c14", name: "HR", description: "Strengths, weaknesses, salary, conflicts", sortOrder: 14 },
  { id: "c15", name: "Career / Job Switch", description: "Why switching, career goals", sortOrder: 15 },
  { id: "c16", name: "Behavioral", description: "STAR-style 'tell me about a time' and work-style questions", sortOrder: 16 },
];

const now = "2026-09-18T00:00:00.000Z";

export const questions: SeedQuestion[] = [
  {
    id: "q1",
    categoryId: "c04",
    subcategory: "Project Overview",
    question: "Explain your current project.",
    answer:
      "Start with the business problem, then the architecture, then my role, the technologies used, one real challenge and how I solved it, and finally the measurable impact.",
    difficulty: "Medium",
    status: "Prepared",
    keyPoints: [
      { id: "kp1", point: "Business context", sortOrder: 1, completed: false },
      { id: "kp2", point: "Architecture", sortOrder: 2, completed: false },
      { id: "kp3", point: "My role", sortOrder: 3, completed: false },
      { id: "kp4", point: "Technologies", sortOrder: 4, completed: false },
      { id: "kp5", point: "One real challenge", sortOrder: 5, completed: false },
      { id: "kp6", point: "Impact", sortOrder: 6, completed: false },
    ],
    followUps: [
      "Why did you use NiFi?",
      "How did you handle failures?",
      "How did you monitor the pipeline?",
    ],
    tags: ["nifi", "pipeline", "architecture"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-17T00:00:00.000Z",
  },
  {
    id: "q2",
    categoryId: "c03",
    subcategory: "Architecture",
    question: "Explain o9 architecture.",
    answer: "Cover the Enterprise Knowledge Graph, IBPL, the platform layers and how planning models are built on top.",
    difficulty: "Hard",
    status: "Not Prepared",
    keyPoints: [
      { id: "kp7", point: "Enterprise Knowledge Graph", sortOrder: 1, completed: false },
      { id: "kp8", point: "IBPL", sortOrder: 2, completed: false },
      { id: "kp9", point: "Platform layers", sortOrder: 3, completed: false },
    ],
    followUps: ["What is IBPL used for?", "How are measures computed?"],
    tags: ["o9", "ibpl", "ekg"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-16T00:00:00.000Z",
  },
  {
    id: "q3",
    categoryId: "c15",
    subcategory: "Motivation",
    question: "Why are you switching?",
    answer: "Focus on growth and scope, framed positively — never negative about the current employer.",
    difficulty: "Easy",
    status: "Prepared",
    keyPoints: [
      { id: "kp10", point: "Growth", sortOrder: 1, completed: false },
      { id: "kp11", point: "Scope", sortOrder: 2, completed: false },
      { id: "kp12", point: "Stay positive", sortOrder: 3, completed: false },
    ],
    followUps: ["What if we match your current salary?"],
    tags: ["hr", "motivation"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-15T00:00:00.000Z",
  },
  {
    id: "q4",
    categoryId: "c09",
    subcategory: "Execution",
    question: "Explain Spark execution.",
    answer: "Job → stages → tasks, driven by the DAG scheduler; shuffle boundaries create stages; tasks run on executors.",
    difficulty: "Hard",
    status: "Not Prepared",
    keyPoints: [
      { id: "kp13", point: "DAG & stages", sortOrder: 1, completed: false },
      { id: "kp14", point: "Shuffle boundaries", sortOrder: 2, completed: false },
      { id: "kp15", point: "Executors & tasks", sortOrder: 3, completed: false },
    ],
    followUps: ["What causes a shuffle?", "How do you tune partitions?"],
    tags: ["spark", "execution"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-14T00:00:00.000Z",
  },
  {
    id: "q5",
    categoryId: "c01",
    subcategory: "Intro",
    question: "Tell me about yourself.",
    answer: "Present → past → why this role. Keep it under 90 seconds.",
    difficulty: "Easy",
    status: "Prepared",
    keyPoints: [
      { id: "kp16", point: "Present", sortOrder: 1, completed: false },
      { id: "kp17", point: "Past", sortOrder: 2, completed: false },
      { id: "kp18", point: "Why this role", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["intro"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    id: "q6",
    categoryId: "c07",
    subcategory: "Joins",
    question: "Difference between INNER and LEFT JOIN?",
    answer: "INNER keeps only matching rows; LEFT keeps all left rows with NULLs where no match.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "kp19", point: "Matching semantics", sortOrder: 1, completed: false },
      { id: "kp20", point: "NULL behavior", sortOrder: 2, completed: false },
    ],
    followUps: ["When would a LEFT JOIN produce duplicates?"],
    tags: ["sql", "joins"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q7",
    categoryId: "c04",
    subcategory: "Project Walkthrough",
    question: "Walk me through your project.",
    answer:
      "Set the scene (business problem + goal), then the end-to-end architecture (sources → ingestion → processing → storage → serving), your specific role and decisions, the tech stack and why, one hard problem you solved, and the measurable outcome.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "kp21", point: "Business problem & goal", sortOrder: 1, completed: false },
      { id: "kp22", point: "End-to-end architecture", sortOrder: 2, completed: false },
      { id: "kp23", point: "My role & key decisions", sortOrder: 3, completed: false },
      { id: "kp24", point: "Tech stack & why", sortOrder: 4, completed: false },
      { id: "kp25", point: "A hard problem I solved", sortOrder: 5, completed: false },
      { id: "kp26", point: "Measurable outcome", sortOrder: 6, completed: false },
    ],
    followUps: [
      "What would you do differently?",
      "How did you ensure data quality?",
      "How does it scale?",
    ],
    tags: ["project", "architecture", "walkthrough"],
    createdAt: now,
    updatedAt: now,
  },

  // ---- Universal interview questions (answer = how to answer, not an answer) ----
  {
    id: "u01",
    categoryId: "c01",
    subcategory: "Opening",
    question: "Walk me through your resume / background.",
    answer:
      "How to answer:\n1. Go chronological but selective — hit only the roles that matter for this job.\n2. For each: what the company did, your role, one signature result.\n3. Explain the transitions (why you moved) as a deliberate progression.\n4. Land on the present and why this role is the logical next step.\n5. Keep it to ~2 minutes; invite them to dig into any part.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u01k1", point: "Chronological but selective", sortOrder: 1, completed: false },
      { id: "u01k2", point: "Role + one result each", sortOrder: 2, completed: false },
      { id: "u01k3", point: "Explain transitions", sortOrder: 3, completed: false },
      { id: "u01k4", point: "Bridge to this role", sortOrder: 4, completed: false },
    ],
    followUps: [],
    tags: ["intro", "resume"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u02",
    categoryId: "c01",
    subcategory: "Motivation",
    question: "Why are you interested in this role?",
    answer:
      "How to answer:\n1. Name 2–3 specifics from the job description that genuinely excite you.\n2. Tie each to something you've done or want to grow into.\n3. Connect it to your trajectory — why now, why this.\n4. Show you understand what success in the role looks like.\n5. Avoid generic praise; be concrete about the work itself.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u02k1", point: "Specifics from the JD", sortOrder: 1, completed: false },
      { id: "u02k2", point: "Tie to your experience", sortOrder: 2, completed: false },
      { id: "u02k3", point: "Why now / why this", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["intro", "motivation"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u03",
    categoryId: "c01",
    subcategory: "Company fit",
    question: "Why do you want to work at this company?",
    answer:
      "How to answer:\n1. Show you researched: mission, product, recent news, or team.\n2. Pick what authentically resonates and say why.\n3. Link their direction to your skills and goals.\n4. Signal culture fit with a concrete reason, not flattery.\n5. Make it clear you chose them, not just 'a job'.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u03k1", point: "Show real research", sortOrder: 1, completed: false },
      { id: "u03k2", point: "What resonates & why", sortOrder: 2, completed: false },
      { id: "u03k3", point: "Their direction ↔ your goals", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["intro", "company"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u04",
    categoryId: "c15",
    subcategory: "Motivation",
    question: "Why are you looking to leave your current job?",
    answer:
      "How to answer:\n1. Stay positive — never bad-mouth the current employer.\n2. Frame around what you're moving toward (growth, scope, impact), not running from.\n3. Give one honest, professional reason (e.g. ceiling on growth, new domain).\n4. Connect that gap directly to what this role offers.\n5. Keep it short and forward-looking.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u04k1", point: "Stay positive", sortOrder: 1, completed: false },
      { id: "u04k2", point: "Moving toward, not away", sortOrder: 2, completed: false },
      { id: "u04k3", point: "Tie gap to this role", sortOrder: 3, completed: false },
    ],
    followUps: ["What if we could offer that at your current company?"],
    tags: ["career", "motivation"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u05",
    categoryId: "c15",
    subcategory: "Goals",
    question: "Where do you see yourself in 3–5 years?",
    answer:
      "How to answer:\n1. Show ambition plus realism — growth in depth and scope.\n2. Describe the kind of problems/impact you want, not a rigid title.\n3. Make the path plausibly run through this role/company.\n4. Signal commitment without over-promising.\n5. Keep it aligned to the role's natural progression.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u05k1", point: "Ambition + realism", sortOrder: 1, completed: false },
      { id: "u05k2", point: "Impact over titles", sortOrder: 2, completed: false },
      { id: "u05k3", point: "Path runs through this role", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["career", "goals"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u06",
    categoryId: "c15",
    subcategory: "Motivation",
    question: "What motivates you?",
    answer:
      "How to answer:\n1. Name 1–2 genuine drivers (solving hard problems, ownership, impact, learning).\n2. Back each with a short real example.\n3. Connect those drivers to what this role provides day-to-day.\n4. Keep it authentic — avoid clichés you can't defend.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u06k1", point: "1–2 genuine drivers", sortOrder: 1, completed: false },
      { id: "u06k2", point: "Back with an example", sortOrder: 2, completed: false },
      { id: "u06k3", point: "Link to the role", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["career", "motivation"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u07",
    categoryId: "c14",
    subcategory: "Self-assessment",
    question: "What are your greatest strengths?",
    answer:
      "How to answer:\n1. Pick 2–3 strengths relevant to this role (check the JD).\n2. For each, give a one-line proof point / result.\n3. Prefer a mix of a hard skill and a working-style strength.\n4. Be specific and measurable, not generic adjectives.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u07k1", point: "Relevant to the JD", sortOrder: 1, completed: false },
      { id: "u07k2", point: "Proof point each", sortOrder: 2, completed: false },
      { id: "u07k3", point: "Specific, not generic", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["hr", "strengths"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u08",
    categoryId: "c14",
    subcategory: "Self-assessment",
    question: "What is your biggest weakness?",
    answer:
      "How to answer:\n1. Pick a real, non-fatal weakness (not a disguised strength).\n2. State it honestly and briefly.\n3. Spend most of the answer on what you're actively doing to improve.\n4. Show self-awareness and progress with a concrete example.\n5. Avoid anything core to the role's must-haves.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u08k1", point: "Real, non-fatal", sortOrder: 1, completed: false },
      { id: "u08k2", point: "Focus on improvement", sortOrder: 2, completed: false },
      { id: "u08k3", point: "Show progress", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["hr", "weakness"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u09",
    categoryId: "c14",
    subcategory: "Self-assessment",
    question: "What are you most proud of? / Your biggest achievement?",
    answer:
      "How to answer:\n1. Use STAR: set the Situation and Task briefly.\n2. Emphasize your specific Actions and decisions.\n3. Quantify the Result and the impact.\n4. Pick something relevant to the role's demands.\n5. Show what you learned or how it changed you.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u09k1", point: "STAR structure", sortOrder: 1, completed: false },
      { id: "u09k2", point: "Your actions", sortOrder: 2, completed: false },
      { id: "u09k3", point: "Quantify impact", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["hr", "achievement", "star"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u10",
    categoryId: "c14",
    subcategory: "Fit",
    question: "What makes you a good fit for this role?",
    answer:
      "How to answer:\n1. Map your top 3 relevant strengths to the role's key requirements.\n2. Give a proof point for each mapping.\n3. Add the intangible: motivation, culture, how you work.\n4. Close with a confident one-line summary of your fit.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u10k1", point: "Map strengths → requirements", sortOrder: 1, completed: false },
      { id: "u10k2", point: "Proof each", sortOrder: 2, completed: false },
      { id: "u10k3", point: "Confident close", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["hr", "fit"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u11",
    categoryId: "c16",
    subcategory: "STAR",
    question: "Tell me about a time you faced a difficult challenge and how you solved it.",
    answer:
      "How to answer (STAR):\n1. Situation — set context in 1–2 sentences.\n2. Task — what was at stake and your responsibility.\n3. Action — the specific steps YOU took (most of the answer).\n4. Result — the outcome, quantified, plus what you learned.\n5. Pick a challenge relevant to the role's real problems.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u11k1", point: "Situation", sortOrder: 1, completed: false },
      { id: "u11k2", point: "Task", sortOrder: 2, completed: false },
      { id: "u11k3", point: "Action (you)", sortOrder: 3, completed: false },
      { id: "u11k4", point: "Result + learning", sortOrder: 4, completed: false },
    ],
    followUps: ["What would you do differently?"],
    tags: ["behavioral", "star"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u12",
    categoryId: "c16",
    subcategory: "STAR",
    question: "Tell me about a conflict with a coworker or manager.",
    answer:
      "How to answer (STAR):\n1. Situation — the disagreement, stated neutrally and fairly.\n2. Task — why resolving it mattered.\n3. Action — how you listened, communicated, and found common ground.\n4. Result — resolution and the working relationship afterward.\n5. Show empathy and professionalism; never blame the other person.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u12k1", point: "State it fairly", sortOrder: 1, completed: false },
      { id: "u12k2", point: "Listen & communicate", sortOrder: 2, completed: false },
      { id: "u12k3", point: "Resolution + relationship", sortOrder: 3, completed: false },
      { id: "u12k4", point: "No blame", sortOrder: 4, completed: false },
    ],
    followUps: [],
    tags: ["behavioral", "conflict", "star"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u13",
    categoryId: "c16",
    subcategory: "STAR",
    question: "Tell me about a time you failed or made a mistake.",
    answer:
      "How to answer (STAR):\n1. Own a real mistake honestly — no deflection.\n2. Situation/Task — what went wrong and the impact.\n3. Action — how you responded and fixed it.\n4. Result — recovery plus the concrete lesson and change you made.\n5. Emphasize growth and accountability.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u13k1", point: "Own it honestly", sortOrder: 1, completed: false },
      { id: "u13k2", point: "How you fixed it", sortOrder: 2, completed: false },
      { id: "u13k3", point: "Lesson & change", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["behavioral", "failure", "star"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u14",
    categoryId: "c16",
    subcategory: "STAR",
    question: "Tell me about a time you worked under pressure or a tight deadline.",
    answer:
      "How to answer (STAR):\n1. Situation — the pressure and constraint.\n2. Task — what had to be delivered.\n3. Action — how you prioritized, communicated, and executed.\n4. Result — delivered on time (or the trade-off you managed) and impact.\n5. Show composure and good judgment, not just heroics.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u14k1", point: "The constraint", sortOrder: 1, completed: false },
      { id: "u14k2", point: "Prioritize & communicate", sortOrder: 2, completed: false },
      { id: "u14k3", point: "Outcome", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["behavioral", "pressure", "star"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u15",
    categoryId: "c16",
    subcategory: "STAR",
    question: "Tell me about a time you took initiative or led something.",
    answer:
      "How to answer (STAR):\n1. Situation — a gap or opportunity you spotted.\n2. Task — what you decided to own.\n3. Action — how you drove it, influenced others, and executed.\n4. Result — the impact and any lasting change.\n5. Highlight ownership and leadership even without formal authority.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u15k1", point: "Spotted the gap", sortOrder: 1, completed: false },
      { id: "u15k2", point: "Drove & influenced", sortOrder: 2, completed: false },
      { id: "u15k3", point: "Lasting impact", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["behavioral", "leadership", "star"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u16",
    categoryId: "c16",
    subcategory: "STAR",
    question: "Tell me about a time you received difficult feedback.",
    answer:
      "How to answer (STAR):\n1. Situation — the feedback and where it came from.\n2. Task — why it mattered to act on.\n3. Action — how you received it without defensiveness and what you changed.\n4. Result — measurable improvement afterward.\n5. Show coachability and a growth mindset.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u16k1", point: "Received openly", sortOrder: 1, completed: false },
      { id: "u16k2", point: "What you changed", sortOrder: 2, completed: false },
      { id: "u16k3", point: "Improvement after", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["behavioral", "feedback", "star"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u17",
    categoryId: "c16",
    subcategory: "Teamwork",
    question: "Give an example of working in a team.",
    answer:
      "How to answer (STAR):\n1. Situation — the team goal and your role in it.\n2. Task — your specific contribution.\n3. Action — how you collaborated, communicated, and handled differences.\n4. Result — the shared outcome and your part in it.\n5. Balance 'I' and 'we' — show you elevate the team.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u17k1", point: "Your role", sortOrder: 1, completed: false },
      { id: "u17k2", point: "How you collaborated", sortOrder: 2, completed: false },
      { id: "u17k3", point: "Balance I / we", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["behavioral", "teamwork", "star"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u18",
    categoryId: "c16",
    subcategory: "Work style",
    question: "How do you handle stress and pressure?",
    answer:
      "How to answer:\n1. State your practical approach (prioritize, break down, communicate early).\n2. Give a brief real example where it worked.\n3. Show you stay calm and keep quality up.\n4. Mention how you prevent burnout / sustain performance.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u18k1", point: "Concrete approach", sortOrder: 1, completed: false },
      { id: "u18k2", point: "Real example", sortOrder: 2, completed: false },
      { id: "u18k3", point: "Stay calm, keep quality", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["behavioral", "stress"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u19",
    categoryId: "c16",
    subcategory: "Work style",
    question: "How do you prioritize when everything is urgent?",
    answer:
      "How to answer:\n1. Describe your framework (impact vs effort, deadlines, dependencies, stakeholder value).\n2. Mention aligning with your manager/stakeholders on priorities.\n3. Give an example of making a hard trade-off.\n4. Show you communicate what won't get done and why.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "u19k1", point: "A clear framework", sortOrder: 1, completed: false },
      { id: "u19k2", point: "Align with stakeholders", sortOrder: 2, completed: false },
      { id: "u19k3", point: "Communicate trade-offs", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["behavioral", "prioritization"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u20",
    categoryId: "c14",
    subcategory: "Logistics",
    question: "What are your salary expectations?",
    answer:
      "How to answer:\n1. If possible, ask their budgeted range first or defer politely.\n2. Give a researched range (market + your level), not a single number.\n3. Anchor to your value and total compensation, not just base.\n4. Signal flexibility and that fit matters, within reason.\n5. Stay confident and non-apologetic.",
    difficulty: "Hard",
    status: "Not Prepared",
    keyPoints: [
      { id: "u20k1", point: "Ask/defer first", sortOrder: 1, completed: false },
      { id: "u20k2", point: "Researched range", sortOrder: 2, completed: false },
      { id: "u20k3", point: "Anchor to value", sortOrder: 3, completed: false },
    ],
    followUps: ["What's your current compensation?"],
    tags: ["hr", "salary"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "u21",
    categoryId: "c14",
    subcategory: "Closing",
    question: "Do you have any questions for us?",
    answer:
      "How to answer:\n1. Always have 2–3 thoughtful questions ready.\n2. Ask about the team, success metrics for the role, or current challenges.\n3. Ask something that shows you researched the company/product.\n4. Avoid asking only about salary/perks here.\n5. End by reaffirming your interest.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "u21k1", point: "Have 2–3 ready", sortOrder: 1, completed: false },
      { id: "u21k2", point: "Team / metrics / challenges", sortOrder: 2, completed: false },
      { id: "u21k3", point: "Reaffirm interest", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["hr", "closing"],
    createdAt: now,
    updatedAt: now,
  },
];
