import type { Category, Question } from "./types";

// Seed rows omit answerLocked — the DB defaults it to false on insert.
type SeedQuestion = Omit<Question, "answerLocked">;

// Phase 0 seed data. In Phase 1 this file is replaced by Supabase queries;
// nothing else in the app imports the data directly — it all goes through
// src/lib/data.ts, so the swap is contained.

export const categories: Category[] = [
  { id: "c01", name: "Introduction", description: "Tell-me-about-yourself and career introduction", sortOrder: 1 },
  { id: "c02", name: "Current Role", description: "Day-to-day, responsibilities, team", sortOrder: 2 },
  { id: "c03", name: "o9 Platform", description: "o9 platform, IBPL, modules, planning", sortOrder: 3 },
  { id: "c04", name: "Project Experience", description: "Current/past project questions and scenarios", sortOrder: 4 },
  { id: "c05", name: "Supply Chain", description: "Demand, supply, S&OP concepts", sortOrder: 5 },
  { id: "c06", name: "Integration", description: "Data integration, connectors, pipelines", sortOrder: 6 },
  { id: "c07", name: "SQL", description: "Queries, tuning, modeling", sortOrder: 7 },
  { id: "c08", name: "PySpark", description: "DataFrames, transformations, tuning", sortOrder: 8 },
  { id: "c09", name: "Spark", description: "Execution model, internals", sortOrder: 9 },
  { id: "c10", name: "Databricks", description: "Jobs, clusters, Delta", sortOrder: 10 },
  { id: "c11", name: "Azure", description: "ADF, ADLS, Synapse", sortOrder: 11 },
  { id: "c12", name: "AWS", description: "S3, Glue, EMR, Redshift", sortOrder: 12 },
  { id: "c13", name: "Scenario Based", description: "Production issues, failures, debugging", sortOrder: 13 },
  { id: "c14", name: "HR", description: "Strengths, weaknesses, salary, conflicts", sortOrder: 14 },
  { id: "c15", name: "Career / Job Switch", description: "Why switching, career goals", sortOrder: 15 },
];

const now = "2026-09-18T00:00:00.000Z";

export const questions: SeedQuestion[] = [
  {
    id: "q1",
    categoryId: "c04",
    subcategory: "Project Overview",
    question: "Explain your current project.",
    answer:
      "Start with the business problem, then the architecture, then my role, the technologies used, one real challenge and how I solved it, and finally the measurable impact.",
    difficulty: "Medium",
    status: "Prepared",
    keyPoints: [
      { id: "kp1", point: "Business context", sortOrder: 1, completed: false },
      { id: "kp2", point: "Architecture", sortOrder: 2, completed: false },
      { id: "kp3", point: "My role", sortOrder: 3, completed: false },
      { id: "kp4", point: "Technologies", sortOrder: 4, completed: false },
      { id: "kp5", point: "One real challenge", sortOrder: 5, completed: false },
      { id: "kp6", point: "Impact", sortOrder: 6, completed: false },
    ],
    followUps: [
      "Why did you use NiFi?",
      "How did you handle failures?",
      "How did you monitor the pipeline?",
    ],
    tags: ["nifi", "pipeline", "architecture"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-17T00:00:00.000Z",
  },
  {
    id: "q2",
    categoryId: "c03",
    subcategory: "Architecture",
    question: "Explain o9 architecture.",
    answer: "Cover the Enterprise Knowledge Graph, IBPL, the platform layers and how planning models are built on top.",
    difficulty: "Hard",
    status: "Not Prepared",
    keyPoints: [
      { id: "kp7", point: "Enterprise Knowledge Graph", sortOrder: 1, completed: false },
      { id: "kp8", point: "IBPL", sortOrder: 2, completed: false },
      { id: "kp9", point: "Platform layers", sortOrder: 3, completed: false },
    ],
    followUps: ["What is IBPL used for?", "How are measures computed?"],
    tags: ["o9", "ibpl", "ekg"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-16T00:00:00.000Z",
  },
  {
    id: "q3",
    categoryId: "c15",
    subcategory: "Motivation",
    question: "Why are you switching?",
    answer: "Focus on growth and scope, framed positively — never negative about the current employer.",
    difficulty: "Easy",
    status: "Prepared",
    keyPoints: [
      { id: "kp10", point: "Growth", sortOrder: 1, completed: false },
      { id: "kp11", point: "Scope", sortOrder: 2, completed: false },
      { id: "kp12", point: "Stay positive", sortOrder: 3, completed: false },
    ],
    followUps: ["What if we match your current salary?"],
    tags: ["hr", "motivation"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-15T00:00:00.000Z",
  },
  {
    id: "q4",
    categoryId: "c09",
    subcategory: "Execution",
    question: "Explain Spark execution.",
    answer: "Job → stages → tasks, driven by the DAG scheduler; shuffle boundaries create stages; tasks run on executors.",
    difficulty: "Hard",
    status: "Not Prepared",
    keyPoints: [
      { id: "kp13", point: "DAG & stages", sortOrder: 1, completed: false },
      { id: "kp14", point: "Shuffle boundaries", sortOrder: 2, completed: false },
      { id: "kp15", point: "Executors & tasks", sortOrder: 3, completed: false },
    ],
    followUps: ["What causes a shuffle?", "How do you tune partitions?"],
    tags: ["spark", "execution"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-14T00:00:00.000Z",
  },
  {
    id: "q5",
    categoryId: "c01",
    subcategory: "Intro",
    question: "Tell me about yourself.",
    answer: "Present → past → why this role. Keep it under 90 seconds.",
    difficulty: "Easy",
    status: "Prepared",
    keyPoints: [
      { id: "kp16", point: "Present", sortOrder: 1, completed: false },
      { id: "kp17", point: "Past", sortOrder: 2, completed: false },
      { id: "kp18", point: "Why this role", sortOrder: 3, completed: false },
    ],
    followUps: [],
    tags: ["intro"],
    createdAt: now,
    updatedAt: now,
    lastReviewedAt: "2026-09-18T00:00:00.000Z",
  },
  {
    id: "q6",
    categoryId: "c07",
    subcategory: "Joins",
    question: "Difference between INNER and LEFT JOIN?",
    answer: "INNER keeps only matching rows; LEFT keeps all left rows with NULLs where no match.",
    difficulty: "Easy",
    status: "Not Prepared",
    keyPoints: [
      { id: "kp19", point: "Matching semantics", sortOrder: 1, completed: false },
      { id: "kp20", point: "NULL behavior", sortOrder: 2, completed: false },
    ],
    followUps: ["When would a LEFT JOIN produce duplicates?"],
    tags: ["sql", "joins"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "q7",
    categoryId: "c04",
    subcategory: "Project Walkthrough",
    question: "Walk me through your project.",
    answer:
      "Set the scene (business problem + goal), then the end-to-end architecture (sources → ingestion → processing → storage → serving), your specific role and decisions, the tech stack and why, one hard problem you solved, and the measurable outcome.",
    difficulty: "Medium",
    status: "Not Prepared",
    keyPoints: [
      { id: "kp21", point: "Business problem & goal", sortOrder: 1, completed: false },
      { id: "kp22", point: "End-to-end architecture", sortOrder: 2, completed: false },
      { id: "kp23", point: "My role & key decisions", sortOrder: 3, completed: false },
      { id: "kp24", point: "Tech stack & why", sortOrder: 4, completed: false },
      { id: "kp25", point: "A hard problem I solved", sortOrder: 5, completed: false },
      { id: "kp26", point: "Measurable outcome", sortOrder: 6, completed: false },
    ],
    followUps: [
      "What would you do differently?",
      "How did you ensure data quality?",
      "How does it scale?",
    ],
    tags: ["project", "architecture", "walkthrough"],
    createdAt: now,
    updatedAt: now,
  },
];
